name: emotion_estimation
channels:
  - numba
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=0.11.0=py37h89c1867_0
  - aiohttp=3.7.3=py37h5e8e339_1
  - astroid=2.4.2=py37hc8dfbb8_1
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - blosc=1.21.0=h9c3ff4c_0
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - cairo=1.14.12=he6fea26_5
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.4=py37hc58025e_1
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.3.1=py37h7f0c10b_1
  - cycler=0.10.0=py_2
  - deepdish=0.3.6=pyh9f0ad1d_0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.2.1=h9c3ff4c_2
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.55.0=0
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-oauthlib=0.4.1=py_2
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.35.0=py37hb27c1af_0
  - harfbuzz=1.9.0=h08d66d9_0
  - hdf5=1.10.2=hc401514_3
  - icc_rt=2020.2=intel_254
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - imbalanced-learn=0.7.0=py_1
  - importlib-metadata=3.4.0=py37h89c1867_0
  - isort=5.7.0=pyhd8ed1ab_0
  - jasper=2.0.14=h07fcdf6_1
  - joblib=1.0.0=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py37h2527ec5_1
  - lazy-object-proxy=1.4.3=py37h8f50634_2
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.15=h516909a_1006
  - libllvm10=10.0.1=hbcb73fb_5
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.14.0=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.0.9=he6b73bb_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxgboost=1.3.3=h9c3ff4c_2
  - libxml2=2.9.9=h13577e0_2
  - llvm-openmp=11.0.1=h4bd325d_0
  - llvmlite=0.35.0=py37h612dafd_4
  - lzo=2.10=h516909a_1000
  - markdown=3.3.3=pyh9f0ad1d_0
  - matplotlib-base=3.1.1=py37hfd891ef_0
  - mccabe=0.6.1=py_1
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py37h8f50634_2
  - mkl_fft=1.2.0=py37h161383b_1
  - mkl_random=1.2.0=py37h9fdb41a_1
  - mlxtend=0.18.0=pyhd3deb0d_0
  - multidict=5.1.0=py37h5e8e339_1
  - ncurses=6.2=h58526e2_4
  - nettle=3.3=0
  - neurokit2=0.1.0=pyh050c7b8_0
  - ninja=1.10.2=h4bd325d_0
  - numba=0.52.0=py37ha9443f7_0
  - numexpr=2.7.2=py37hdc94413_0
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1j=h7f98852_0
  - pandas=0.25.3=py37he6710b0_0
  - pcre=8.44=he1b5a44_0
  - pickle5=0.0.11=py37h8f50634_0
  - pillow=5.4.1=py37h34e0f95_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.34.0=h14c3975_1003
  - protobuf=3.14.0=py37hcd2ae1e_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=3.4.2=py37hb342d67_1
  - py-xgboost=1.3.3=py37h89c1867_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pylint=2.6.0=py37_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.9=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7=pyhd3deb0d_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.6.0=py37h91f5cce_0
  - setuptools=49.6.0=py37h89c1867_3
  - six=1.15.0=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - sqlite=3.34.0=h74cdb3f_0
  - tbb=2020.3=hfd86e86_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.58.0=pyhd8ed1ab_0
  - typed-ast=1.4.2=py37h5e8e339_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.11.2=py37h8f50634_1
  - x264=1!152.20180806=h14c3975_0
  - xgboost=1.3.3=py37h89c1867_2
  - xlrd=1.2.0=py37_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py37h5e8e339_1
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - pip:
    - mne==0.22.0
    - peakutils==1.3.3
    - pysiology==0.0.9.4
    - samplerate==0.1.0
    - tables==3.6.1
prefix: /home/sujjavapapu/miniconda3/envs/ss_emotion